confidential-containers/kbs-types

src/lib.rs
Starting 1.63.0, clippy suggests to derive Eq where it's possible and
PartialEq is derived. Do that to fix its warnings.
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> Derive Eq with PartialEq to satisfy clippy

Cargo.toml
Adjust internal version to reflect the version of the KBS protocol implemented in this crate (v0.1.0).
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> Prepare to release v0.1.0

src/lib.rs
It is specified in the KBS OpenAPI document. It is used for carrying extra information back to the client when return an HTTP error.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
=> Add the ErrorInformation payload

src/lib.rs, src/tee/snp.rs
The current `mod` parameter of the `TeePubKey` struct both is a short form for the modulus of an RSA public key, but is also confused by Rust as the `mod` keyword. I propose removing the `r#mod` code and would prefer to just call the parameter `k_mod` (in JSON, `k-mod`). This isn't a big issue and can easily be dropped if others disagree.
For adding the generation parameter to `SnpAttestation`: currently in `reference-kbs`, our ASK and ARK keys are distinguished by their generation (i.e. Milan ASK and ARKs differ from Genoa ASK and ARKs). Thus, to know which key pair to retrieve, we need to know which generation we are currently attesting for.
=> SNP: Edit TeePubKey and add generation to SnpRequest

Cargo.toml, src/lib.rs
This is an azure specific TEE entry. Azure CVMs today provide a discrete method to retrieve Attestation Evidence in an SEV-SNP guest via vTPM. Details can be found [here](https://github.com/Azure/confidential-computing-cvm-guest-attestation/blob/main/cvm-guest-attestation.md#linux).
We're adding this entry because kbs-types is consumed by CoCo's Attestation Agent/Service, for which we are creating attester and verifier cc_kbc modules.
=> Add azure sev-snp vtpm-based TEE

CODEOWNERS
As downstream consumers of the kbs-types crate, the Confidential Containers kbs, attestation-service and attestation-agent crates should be notified of any new release, breaking changes, etc.
As a maintainer for the CoCo project, adding myself to the CODEOWNERS file will facilitate that.
=> CODEOWNERS: Shamelessly adding myself

src/lib.rs
The JWA RFC [1] specifies that RSA public keys should define the modulus and exponent fields as `n` and `e` respectively.
[1] https://www.rfc-editor.org/rfc/rfc7518.html#page-30
=> kbs-types: Use JWK specified fields

Cargo.toml, src/lib.rs, src/tee/sev.rs
Both EC and RSA JWK-formatted public keys must specify a key type through the `kty` type.
See https://www.rfc-editor.org/rfc/rfc7518.html#section-6 for further reference.
=> kbs-types: Add a key type field for publick keys

Cargo.toml
The `tee-snp` feature enables the `sev` dependency but it doesn't actually use anything from that crate, so let's remove it to minimize dependencies.
=> Fix `tee-snp` dependencies

Cargo.toml, src/lib.rs, src/tee/sev.rs, src/tee/snp.rs
It can be useful to use this crate in bare-metal code where `std` is not available (e.g. SVSM).
So let's provide 2 new features (`std` and `alloc`) to support this use case. `std` is enabled by default.
As long as there is a memory allocator, we can still use this crate without the rest of the standard library by enabling the `alloc` feature:
`kbs-types = { version = "...", default-features = false,
features = ["alloc"] }`
The patch is based on what serde does to handle the same use case.
=> Add new features to use this crate without the standard library

src/lib.rs
This is a new TEE type for Intel TDX VMs on Azure that rely on a vTPM for attestation
=> Add AzTdxVtpm tee type

src/lib.rs
The original KBS Protocol's `Response` follows RFC7519's JWE definition. Now it is lacked of `aad` field for AEAD. Also, this patch adds the definition for `ProtectedHeader` due to the RFC.
=> Update `Response` struct to follow RFC 7516

src/lib.rs
This is a fix patch to make the `ProtectedHeader` member public, thus downstream can edit the fields.
=> Make ProtectedHeader members public

Cargo.toml
Although not reflected in the Cargo.toml file, version 0.8.0 of this crate was already released.
=> Update to 0.9.0

Cargo.toml, src/error.rs, src/lib.rs
This patch is a fix up to previous commits to update the Response struct to follow RFC7516.
The work included in the commit
1. Make both serialization and deserialization of `ProtectedHeader` use base64-url-nopadding encoding. This means that the whole ProtectedHeader will be serialized into a base64 string, rather than a struct.
2. Make `encrypted_key`, `aad`, `iv`, `ciphertext`, `tag` to base64-url-nopadding encoded string when serializing.
3. Automatical deseralization logic when parsing Response from a flattened JSON JWE Serialization.
4. Add `generate_aad()` function to `ProtectedHeader`
Close #47
=> Apply RFC7516 Standard to Response

src/lib.rs
1. In previous commits we did a duplicated base64 encoding and decoding when serializing/deserializing the AAD field. This patch fixes it.
2. Extend `ProtectedHeader` to allow nested structues for `EC` suites.
=> Response: fix some bugs of Response struct

src/lib.rs
In the KBS protocol, TPMs can be used in order to generate and sign the attestation evidence.
This is required in order to add a TPM verifier in trustee, see https://github.com/confidential-containers/trustee/issues/846
=> Add TPM tee

src/hash_algorithm.rs
removes the accumulate_hash function. Users are expected to call digest() instead. This helps unify the interface and remove duplicate code
Handles comments in https://github.com/confidential-containers/trustee/pull/833
=> remove accumulate_hash from HashAlgorithm

Cargo.toml, src/hash_algorithm.rs
sm3 is a cryptographic hash function defined in OSCCA GM/T 0004-2012, which is used in CCEL integrity calculation.
=> hash algorithm: add sm3 algorithm

src/lib.rs
This was an oversight, make these fields public.
=> lib: Make CompositeEvidence fields public

Cargo.toml, src/lib.rs
Often, TeePubKeys are serialized to JSON format. The rust ear library provides equivalent types for representing data, including an EAR map. Allow for serialization of a TeePubKey to an EAR map and ensure that this map can be deserialized as a JSON object in return.
@Xynnn007 this fixes the producer problem mentioned [here](https://github.com/confidential-containers/trustee/pull/959#pullrequestreview-3226882770).
=> lib: Serialize TeePubKey to EAR map
